#!/bin/bash

main() {
  sourceFiles
  updateOS
  installPacmanPackages
  mksrc
  installYayPackages
  installtpm
  installRust
  buildNeovim
  addProgramsNeoVimInterfacesWith
  deleteSymLinks
  createSymLinks
  zshshell
}

sourceFiles() {
  missingFile=0

  files=(packages)
  for f in ${files[@]}
  do
    source $f
  done

  [[ $missingFile == 1 ]] && echo 'Missing file(s) program exiting.' && exit

}

updateOS() {
  echo 'Updating System' &&
  sudo pacman -Syyuu --noconfirm
}

installPacmanPackages() {
  echo 'Installing pacman packages.' &&
  sudo pacman -Syyuu --noconfirm ${pacman_packages[@]}
}

installYayPackages() {
   echo 'Installing yay packages.' &&
   yay -Syu --noconfirm ${yay_packages[@]}
}

installRust() {
  echo 'Installing rustup.' &&
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}

deleteSymLinks() {
     echo "Deleting symlinks."
     rm -rfv ~/.config/Thunar
     rm -rfv ~/.config/nvim
     rm -rfv ~/.config/ranger
     rm -rfv ~/.config/starship
     rm -rfv ~/.config/tmux
     rm -rfv ~/.config/zsh
     rm -fsv ~/.scripts
     rm -rfv ~/.gitconfig
     rm -fsv ~/.tmux.conf
     rm -rfv ~/.zshenv
 }

createSymLinks() {
    echo "Creating symlinks."
    ln -fsv $HOME/git/do75/config/btop                         $HOME/.config/btop
    ln -fsv $HOME/git/do75/config/nvim	                       $HOME/.config/nvim
    ln -fsv $HOME/git/do75/config/ranger                       $HOME/.config/ranger
    ln -fsv $HOME/git/do75/config/starship                     $HOME/.config/starship
    ln -fsv $HOME/git/do75/config/wezterm                      $HOME/.config/wezterm
    ln -fsv $HOME/git/do75/config/zsh                          $HOME/.config/zsh
    ln -fsv $HOME/git/do75/scripts                             $HOME/.scripts
    ln -fsv $HOME/git/do75/wallpapers                          $HOME/.wallpapers
    ln -fsv $HOME/git/do75/gitconfig                           $HOME/.gitconfig
    ln -fsv $HOME/git/do75/tmux.conf                           $HOME/.tmux.conf
    ln -fsv $HOME/git/do75/zshenv                              $HOME/.zshenv
}

zshshell() {
  sudo chsh -s /bin/zsh $USER
}

main $@
