#!/bin/bash
# {{{ Notes
#
# Notes:
#   1) 0 == false && 1 == true ... Duh!
#   2) Options are listed alphabetically only because I scan them faster.
#
# -------------------------------------------------------------------------- }}}
# {{{ Products to install.

neovimBuildFlag=1
osUpdateFlag=1
pacmanPackagesFlag=1
paruPackagesFlag=1
yayPackagesFlag=1
pipPackagesFlag=1
rbenvFlag=1
rustFlag=1
symlinksFlag=1
tmuxPluginsFlag=1

# -------------------------------------------------------------------------- }}}
# {{{ Other variables used during product installation.

# The root personal repositories are cloned to.
cloneRoot=$DOTFILES

# The email assiciated with git commit messages.
gitEmail="nickflip86@gmail.com"

# Git user namn used for commit messages.
gitUserName="5nik7"

# Ruby version to install.  rbenv is the Ruby enviornment manager.
# rubyVerion becomes the global Ruby version installed.
rubyVersion='3.2.0'


# -------------------------------------------------------------------------- }}}
